graph TB
    subgraph Hotspots
        F0[pom.xml<br/>HIGH]
        F1[readme.md<br/>HIGH]
        F2[build.gradle<br/>MEDIUM]
        F3[OwnerControllerTests.java<br/>MEDIUM]
        F4[ClinicServiceTests.java<br/>MEDIUM]
        F5[PetController.java<br/>MEDIUM]
        F6[OwnerController.java<br/>MEDIUM]
        F7[Owner.java<br/>MEDIUM]
        F8[VisitController.java<br/>MEDIUM]
        F9[PetControllerTests.java<br/>MEDIUM]
    end
